version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
    
     # login to docker
     - run: echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin

     # build the application image
     - run: docker build -t tufin/img:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push tufin/img:$CIRCLE_BRANCH
